{% set name = "cool_maps" %}
{% set version = "0.0.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/rucool/cool_maps/archive/{{ version }}.tar.gz
  sha256: 1f5c38f72018c001e45e429df91212d0bb68319cc85e4080804696bff2fcf684

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - cartopy
    - matplotlib-base
    - cmocean
    - oceans
    - numpy
    - erddapy

test:
  imports:
    - cool_maps
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/rucool/cool_maps
  summary: 'Wrapper around Cartopy to easily generate nice-looking maps passing just the extent.'
  license: MIT
  license_file: LICENSE
  doc_url: https://cool_maps.readthedocs.io/

extra:
  recipe-maintainers:
    - najascutellatus
