{% set name = "cool_maps" %}
{% set version = "1.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/rucool/cool_maps/archive/{{ version }}.tar.gz
  sha256: 9e49be1c33cb412e2cf672660ab3ed10d6be0da3caabe3d77b5d6596bbf0107a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools
    - versioneer
  run:
    - python >=3.7
    - cartopy
    - matplotlib-base
    - cmocean
    - oceans
    - numpy
    - xarray
    - erddapy

test:
  imports:
    - cool_maps
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/rucool/cool_maps
  summary: 'Wrapper around Cartopy to easily generate nice-looking maps passing just the extent.'
  license: MIT
  license_file: LICENSE
  doc_url: https://cool_maps.readthedocs.io/

extra:
  recipe-maintainers:
    - najascutellatus
    - lnazzaro
    - lgarzio
